apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build-n-deploy

on:
  push:
    branches:
      - "*"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world 11"

      - uses: cloudbees-io/checkout@v1

      - name: build code
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          go version
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o build/api-server .

      - uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          role-to-assume: service-ecr-role
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max

      - uses: cloudbees-io/configure-ecr-credentials@v1

      - uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/simple-go-api-server-image:latest

      - id: helmpkg
        name: Package Helm chart
        uses: cloudbees-io/helm-package
        with:
          chart: ./charts/myapp
          destination: ./packaged-charts
          version: "0.0.1"
          values: |
            image:
              repository:  ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/simple-go-api-server-image
              tag: latest

      - name: Publish Helm chart
        uses: cloudbees-io/helm-push
        with:
          chart: ${{ steps.helmpkg.outputs.chart }}
          remote: oci://${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com

    outputs:
      chart-location: oci://${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/simple-go-api-server
      chart-version: "0.0.1"

  deploy:
    needs:
      - build

    steps:
      - uses: cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          role-to-assume: service-eks-role
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max

      - uses: cloudbees-io/configure-eks-credentials@v1
        with:
          name: arch-saas

      - uses: cloudbees-io/configure-ecr-credentials@v1

      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install
        with:
          chart-location: ${{ needs.build.outputs.chart-location }}
          version: ${{ needs.build.outputs.chart-version }}
          release-name: app-chart
          namespace: simple-go-api-server
